
export const CARD_TYPE_VIRUS = 'CARD_TYPE_VIRUS';
export const CARD_TYPE_RESOURCE = 'CARD_TYPE_RESOURCE';
export const CARD_TYPE_ADVANTAGE = 'CARD_TYPE_ADVANTAGE';
export const CARD_TYPE_DISADVANTAGE = 'CARD_TYPE_DISADVANTAGE';
export const ACTION_INCREMENT_VIRUS_TOKEN = 'ACTION_INCREMENT_VIRUS_TOKEN';
export const ACTION_INCREMENT_VIRUS_TOKEN_CARD = 'ACTION_INCREMENT_VIRUS_TOKEN_CARD';
export const ACTION_CONTAIN_VIRUS = 'ACTION_CONTAIN_VIRUS';
export const ACTION_DESTROY_VIRUS_TOKEN = 'ACTION_DESTROY_VIRUS_TOKEN';
export const ACTION_PREVENT_FROM_NEIGHBOR_INFECTION = 'ACTION_PREVENT_FROM_NEIGHBOR_INFECTION';
export const ACTION_PREVENT_RESOURCE = 'ACTION_PREVENT_RESOURCE';
