
export const CARD_TYPE_VIRUS = 'CARD_TYPE_VIRUS';
export const CARD_TYPE_RESOURCE = 'CARD_TYPE_RESOURCE';
export const CARD_TYPE_ADVANTAGE = 'CARD_TYPE_ADVANTAGE';
export const CARD_TYPE_DISADVANTAGE = 'CARD_TYPE_DISADVANTAGE';

export const ACTION_INCREMENT_VIRUS_TOKEN = 'ACTION_INCREMENT_VIRUS_TOKEN';
export const ACTION_INCREMENT_VIRUS_TOKEN_CARD = 'ACTION_INCREMENT_VIRUS_TOKEN_CARD';
export const ACTION_CONTAIN_VIRUS = 'ACTION_CONTAIN_VIRUS';
export const ACTION_DESTROY_VIRUS_TOKEN = 'ACTION_DESTROY_VIRUS_TOKEN';
export const ACTION_PREVENT_FROM_NEIGHBOR_INFECTION = 'ACTION_PREVENT_FROM_NEIGHBOR_INFECTION';
export const ACTION_PREVENT_RESOURCE = 'ACTION_PREVENT_RESOURCE';

export const GM_NEXT_TURN = 'GM_NEXT_TURN';
export const GM_BEGIN_TURN = 'GM_BEGIN_TURN';
export const GM_FINISH_TURN = 'GM_FINISH_TURN';
export const GM_DRAW_CARD = 'GM_DRAW_CARD';
export const GM_PLAY_CARD = 'GM_PLAY_CARD';
export const GM_ADVANCE_TURN = 'GM_ADVANCE_TURN';
export const GM_START_GAME = 'GM_START_GAME';
export const GM_CHAT_MESSAGE = 'GM_CHAT_MESSAGE';

export const GAME_STATE_WAITING_PLAYERS = 'GAME_STATE_WAITING_PLAYERS';
export const GAME_STATE_STARTED = 'GAME_STATE_STARTED';
export const GAME_STATE_OVER = 'GAME_STATE_OVER';

