
export const CARD_TYPE_VIRUS = 'CARD_TYPE_VIRUS';
export const CARD_TYPE_RESOURCE = 'CARD_TYPE_RESOURCE';
export const CARD_TYPE_ADVANTAGE = 'CARD_TYPE_ADVANTAGE';
export const CARD_TYPE_DISADVANTAGE = 'CARD_TYPE_DISADVANTAGE';

export const ACTION_INCREMENT_VIRUS_TOKEN = 'ACTION_INCREMENT_VIRUS_TOKEN';
export const ACTION_INCREMENT_VIRUS_TOKEN_CARD = 'ACTION_INCREMENT_VIRUS_TOKEN_CARD';
export const ACTION_CONTAIN_VIRUS = 'ACTION_CONTAIN_VIRUS';
export const ACTION_DESTROY_VIRUS_TOKEN = 'ACTION_DESTROY_VIRUS_TOKEN';
export const ACTION_PREVENT_FROM_NEIGHBOR_INFECTION = 'ACTION_PREVENT_FROM_NEIGHBOR_INFECTION';
export const ACTION_PREVENT_CARD_ACTION = 'ACTION_PREVENT_CARD_ACTION';
export const ACTION_NEIGHBOUR_INFECTION = 'ACTION_NEIGHBOUR_INFECTION';


export const GM_NEXT_TURN = 'GM_NEXT_TURN';
export const GM_BEGIN_TURN = 'GM_BEGIN_TURN';
export const GM_FINISH_TURN = 'GM_FINISH_TURN';
export const GM_DRAW_CARD = 'GM_DRAW_CARD';
export const GM_PLAY_CARD = 'GM_PLAY_CARD';
export const GM_ADVANCE_TURN = 'GM_ADVANCE_TURN';
export const GM_START_GAME = 'GM_START_GAME';
export const GM_CHAT_MESSAGE = 'GM_CHAT_MESSAGE';
export const GM_END_NEW_ROUND_ANIMATIONS = 'GM_END_NEW_ROUND_ANIMATIONS';

export const GAME_STATE_WAITING_PLAYERS = 'GAME_STATE_WAITING_PLAYERS';
export const GAME_STATE_STARTED = 'GAME_STATE_STARTED';
export const GAME_STATE_OVER = 'GAME_STATE_OVER';
export const GAME_STATE_VICTORY_END = 'GAME_STATE_VICTORY_END';

export const ROUND_STATE_INITIAL_DRAW = 'ROUND_STATE_INITIAL_DRAW';
export const ROUND_STATE_VIRUS_PHASE = 'ROUND_STATE_VIRUS_PHASE';
export const ROUND_STATE_PLAYERS_PHASE = 'ROUND_STATE_PLAYERS_PHASE';

export const TOKENS_SPREAD_THRESHOLD = 4;
export const MAX_VIRUS_CARD_PER_PLAYER = 4;

export const SERVER_ERROR = "SERVER_ERROR";

